# consumer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      imagePullSecrets:
      - name: gcp-artifact-registry-key
      
      volumes:
      - name: cloudsql-key-volume
        secret:
          secretName: gcp-cloudsql-key

      containers:
      - name: consumer
        image: asia-south2-docker.pkg.dev/quiet-spirit-475711-g3/statusbus-repo/consumer:latest
        envFrom:
        - secretRef:
            name: statusbus-postgres-credentials
        - secretRef:
            name: statusbus-redis-connection
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@127.0.0.1:5432/statusbus?schema=public"
        resources:
          requests:
            memory: "256Mi"
            cpu: "350m"
          limits:
            memory: "768Mi"
            cpu: "500m"
      
      # gcp cloud-sql sidecar
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
        args:
          - "--structured-logs"
          - "--port=5432"
          - "--credentials-file=/secrets/key.json"
          - "quiet-spirit-475711-g3:asia-south2:statusbus-postgres"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: cloudsql-key-volume
          mountPath: /secrets/
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "300m"