# fe-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      imagePullSecrets:
      - name: gcp-artifact-registry-key
      
      volumes:
      - name: cloudsql-key-volume
        secret:
          secretName: gcp-cloudsql-key

      containers:
      - name: fe
        image: asia-south2-docker.pkg.dev/quiet-spirit-475711-g3/statusbus-repo/fe:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: statusbus-postgres-credentials
        env:
        # internal 'api-service' for SSR
        - name: API_URL
          value: "http://api-service:3001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
            