apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fe-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Optional: for HTTPS
spec:
  ingressClassName: nginx
  rules:
  - host: byaniket.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fe-service
            port:
              number: 3000

