name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}
  REPOSITORY: statusbus-repo
  SERVICE_NAME: api

jobs:
  detect-change:
    name: detect changes in codebase
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # min 2 commits required for comparison

      - name: check for api changes
        id: changes # give ID to reference the output
        run: |
          echo "Checking for changes in api or packages..."
          # 1. Compare the last commit (HEAD) with the one before it (HEAD^)
          # 2. Grep searches that list of changed files for our paths
          if git diff --name-only HEAD^ HEAD | grep -E '^apps/api/|^packages/' > /dev/null; then
            # 3. If found, set the output variable 'api' to 'true'
            echo "Changes detected."
            echo "api=true" >> $GITHUB_OUTPUT
          else
            echo "No changes found."
            echo "api=false" >> $GITHUB_OUTPUT
          fi
  checkout-and-list:
    name: Checkout and list
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: List files
        run: |
          echo "Hello from the CI pipeline!"
          echo "The repository contains:"
          ls -la
  
  buld-and-push-api:
    name: build and push api image
    runs-on: ubuntu-latest
    needs: [checkout-and-list, detect-change]
           
    if: needs.detect-change.outputs.api == 'true'
    
    steps:
      - uses: actions/checkout@v4

      - name: auth to gcp
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: gcloud sdk setup
        uses: google-github-actions/setup-gcloud@v2

      - name: docker config for artifact registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker buildx build --platform=linux/amd64 \
            -f apps/${{env.SERVICE_NAME}}/Dockerfile \
            -t ${{env.GAR_LOCATION}}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{env.REPOSITORY}}/${{env.SERVICE_NAME}}:${{github.sha}} \
            -t ${{env.GAR_LOCATION}}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{env.REPOSITORY}}/${{env.SERVICE_NAME}}:latest \
            .

      - name: Push Docker Image
        run: |
          docker push ${{env.GAR_LOCATION}}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{env.REPOSITORY}}/${{env.SERVICE_NAME}}:${{github.sha}}
          docker push ${{env.GAR_LOCATION}}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{env.REPOSITORY}}/${{env.SERVICE_NAME}}:latest